### ISSUE TITLE
H5P Image Slider not Displayed in Lernmodule

### ISSUE THREAD

**Issue by iFadi** [studer-raimann/H5PPageComponent#1]
We can add H5P Content in a Lernmodule (s.screenshot) and see it in (working modus) but in (Presentation modus) it does not show up. 

We are using the latest ILIAS 5.3.12 Version, H5P 2.1.2 and H5PPageComponent 1.1.2

<img width="1384" alt="bildschirmfoto 2019-01-30 um 17 46 51" src="https://user-images.githubusercontent.com/1717456/51993410-7a3ddb00-24b7-11e9-978b-14dd88a73a83.png">
<img width="1401" alt="bildschirmfoto 2019-01-30 um 17 46 59" src="https://user-images.githubusercontent.com/1717456/51993416-7ca03500-24b7-11e9-9847-b27ce7c2b27d.png">

**Comment by theodortruffer** [comment]
Hello @iFadi 

Thanks for your report! Unfortunately we don't have the resources to fix bugs in all of our plugins, so we can only provide bug fixing for our customers. Therefore, we can't guarantee you that this bug will be fixed.

If you're interested in a Service License Agreement (https://studer-raimann.ch/en/products/ilias-plugins/plugin-sla/) or you'd like to support the fixing of this bug only, please let us know. 

Kind Regards

**Comment by srgitlab** [comment]
Moved to Jira
